backend/controllers/PatientController.php
<?php

namespace backend\controllers;

use backend\models\search\PrescriptionSearch;
use common\components\utils\PermissionConstant;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use Yii;
use common\models\Patient;
use backend\models\search\PatientSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PatientController implements the CRUD actions for Patient model.
 */
class PatientController extends BackendController
{
    const ACTION_EXPORT = 'export';

    /** @inheritdoc */
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ]);
    }

    /**
     * Lists all Patient models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PatientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (rbac_is_allow_exec(PermissionConstant::EXPORT_PATIENT) && Yii::$app->request->get('act') == self::ACTION_EXPORT) {
            return $this->exportData($dataProvider->getModels());
        }
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Patient model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $searchModel = new PrescriptionSearch();
        $params = ArrayHelper::merge(Yii::$app->request->queryParams, ['PrescriptionSearch' => ['patient_id' => $id]]);
        $dataProvider = $searchModel->search($params);
        return $this->render('view', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Patient model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Patient();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Patient model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Patient model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->softDelete();
        if ($url = Yii::$app->request->get('redirect')) {
            return $this->redirect($url);
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the Patient model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Patient the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Patient::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionFind($term)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $row_set = [];
        $patients = Patient::find()->where([
            'OR',
            ['LIKE', 'fullname', $term],
            ['LIKE', 'phone', $term]
        ])->asArray()->all();
        foreach ($patients as $patient) {
            $row_set[] = [
                'id' => $patient['id'],
                'label' => $patient['fullname'] . ' - ' . $patient['phone'],
                'value' => $patient['fullname'],
                'phone' => $patient['phone'],
                'email' => $patient['email'],
                'year' => $patient['year_of_birth'],
                'gender' => $patient['gender'],
                'province' => $patient['province_id'],
                'district' => $patient['district_id'],
                'ward' => $patient['ward_id'],
                'address' => $patient['address'],
            ];
        }
        //$row_set = ArrayHelper::map($patients,'id', 'fullname');
        return $row_set;
    }

    public function exportData( $dataModel, $file_name = null)
    {
        if (!$file_name) {
            $file_name = "DanhSachBenhNhan-" . date('d-m-Y');
        }

        $spreadsheet = new Spreadsheet();
        // Set document properties
        $alphas = range('A', 'Z');
        $index = 0;
        $row = 2;
        $array = [];
        $columns = ['ID', "Họ và tên", "Số điện thoại", "Email", "Năm sinh", "Giới tính", "Khu vực", "Quận", "Tổng số toa", "Trạng thái", "Tạo lúc"];

        $spreadsheet->getActiveSheet()->mergeCells("A1:J1");
        $spreadsheet->setActiveSheetIndex(0)->setCellValue("A1" , 'Danh sách Khách hàng');
        $spreadsheet->getActiveSheet()->getStyle("A1:J1")->applyFromArray([
            'font' => [
                'bold' => true,
            ],
            'alignment' => [
                'vertical' => Alignment::VERTICAL_CENTER,
                'horizontal' => Alignment::HORIZONTAL_CENTER,
            ]
        ]);

        // Add some data
        foreach ($columns as $column) {
            $spreadsheet->setActiveSheetIndex(0)->setCellValue($alphas[$index] . $row , $column);
            $array[$alphas[$index] . $row] = $column;
            $spreadsheet->getActiveSheet()->getStyle("A{$row}:K{$row}")->applyFromArray([
                'alignment' => [
                    'vertical' => Alignment::VERTICAL_CENTER,
                ],
                'borders' => [
                    'allBorders' => [
                        'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    ]
                ],
                'fill' => [
                    'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                    'startColor' => [
                        'argb' => adjustBrightness('00A9A0', 0.9),
                    ],
                ],
            ]);
            $index++;
        }

        $row = 3;
        // Miscellaneous glyphs, UTF-8

        foreach ($dataModel as $model) {
            /**
             * @var Patient $model
             */
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("A{$row}", $model->id);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("B{$row}", Html::encode($model->fullname));
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("B")->setAutoSize(true);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("C{$row}", Html::encode($model->phone));
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("C")->setAutoSize(true);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("D{$row}", Html::encode($model->email));
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("D")->setAutoSize(true);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("E{$row}", $model->year_of_birth);
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("E")->setAutoSize(true);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("F{$row}", @Patient::genders()[$model->gender]);
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("F")->setAutoSize(true);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("G{$row}", @$model->province->name);
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("G")->setAutoSize(true);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("H{$row}", @$model->district->name);
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("H")->setAutoSize(true);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("I{$row}", $model->count_prescription);
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("I")->setAutoSize(true);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("J{$row}", @Patient::statuses()[$model->status]);
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("J")->setAutoSize(true);
            $spreadsheet->setActiveSheetIndex(0)->setCellValue("K{$row}", Yii::$app->formatter->asDatetime($model->created_at, 'medium'));
            $spreadsheet->setActiveSheetIndex(0)->getColumnDimension("K")->setAutoSize(true);
            $row++;
        }
        //dd1($spreadsheet->getActiveSheet()->toArray(null, true, true, true));
        // Redirect output to a client’s web browser (Xlsx)
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header("Content-Disposition: attachment;filename=$file_name.xlsx");
        header('Cache-Control: max-age=0');
        // If you're serving to IE 9, then the following may be needed
        header('Cache-Control: max-age=1');

        // If you're serving to IE over SSL, then the following may be needed
        header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified

frontend/controllers/PatientController.php
<?php

namespace frontend\controllers;

use frontend\models\search\PrescriptionSearch;
use common\models\Prescription;
use Yii;
use common\models\Patient;
use frontend\models\search\PatientSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PatientController implements the CRUD actions for Patient model.
 */
class PatientController extends FrontendController
{

    /** @inheritdoc */
    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::class,
                    'actions' => [
                        'delete' => ['post'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Patient models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PatientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Patient model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $searchModel = new PrescriptionSearch();
        $params = ArrayHelper::merge(Yii::$app->request->queryParams, ['PrescriptionSearch' => ['patient_id' => $id]]);
        $dataProvider = $searchModel->search($params);
        $lastPrescription = Prescription::find()->where(['patient_id' => $id])->orderBy(['id' => SORT_DESC])->one();
        return $this->render('view', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'lastPrescription' => $lastPrescription
        ]);
    }

    /**
     * Updates an existing Patient model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return [
                'forceReload' => $request->get('pjax-container', '#crud-datatable-pjax'),
                'forceClose' => true,
                'push' => false,
                'replace' => false
            ];
            exit();
        }
        return [
            'title'=> Yii::t('checkin', 'Cập nhật thông tin bệnh nhân'),
            'content'=>$this->renderAjax('_form', [
                'model' => $model,
            ]),
            'footer' => Html::submitButton(Yii::t('backend', 'Cập nhật'), ['class' => 'btn btn-primary'])
        ];
    }

    /**
     * Deletes an existing Patient model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->softDelete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Patient model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Patient the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Patient::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/patient/detail/_detail.php
<?php
use common\models\Patient;
use common\components\utils\Html;
use common\components\utils\PermissionConstant;

/**
 * @var yii\web\View $this
 * @var \common\models\Patient $model
 */
?>
<div class="card">
    <div class="card-body">
        <div class="pt-4 text-center">
          <h5 class="h3 title">
            <span class="d-block mb-1"><?= Html::encode($model->fullname);?></span>
            <span class="badge badge-pill badge-lg <?= $model->status == Patient::STATUS_ACTIVE ? 'badge-success': 'badge-warning';?>"><?= @$model::statuses()[$model->status];?></span>
          </h5>
          <div class="mt-3">
            <?= Html::a('<i class="fa-fw fas fa-edit"></i>', ['/patient/update', 'id' => $model->id], [
                'class' => 'btn btn-primary btn-sm',
                'data-toggle' => 'tooltip',
                'title' => Yii::t('checkin', 'Cập nhật'),
            ], [PermissionConstant::UPDATE_PATIENT]);?>

            <?php
              if($model->status != Patient::STATUS_DELETED) {
                  echo Html::a('<i class="fa-fw fas fa-trash"></i>', ['/patient/delete', 'id' => $model->id], [
                      'class'        => 'btn btn-danger btn-sm',
                      'data-toggle'  => 'tooltip',
                      'data-confirm' => 'Bạn có chắc là sẽ xóa không',
                      'data-method'  => 'post',
                      'title'        => Yii::t('checkin', 'Xoá'),
                  ], [PermissionConstant::DELETE_PATIENT]);
              }
            ?>
          </div>
        </div>
    </div>
    <div class="card-body group-block">
        <div class="item-detail">
            <div class="item-label"><strong><?= Yii::t('checkin', 'Số điện thoại');?></strong></div>
            <div class="item-content"><?= Html::encode($model->phone);?></div>
        </div>
        <div class="item-detail">
            <div class="item-label"><strong><?= Yii::t('checkin', 'Email');?></strong></div>
            <div class="item-content"><?= Html::encode($model->email);?></div>
        </div>
        <div class="item-detail">
          <div class="item-label"><strong><?= Yii::t('checkin', 'Giới tính');?></strong></div>
          <div class="item-content"><?= Html::encode(@$model::genders()[$model->gender]);?></div>
        </div>
        <div class="item-detail">
          <div class="item-label"><strong><?= Yii::t('checkin', 'Năm sinh');?></strong></div>
          <div class="item-content"><?= Html::encode($model->year_of_birth);?></div>
        </div>
        <div class="item-detail">
            <div class="item-label"><strong><?= Yii::t('checkin', 'Địa chỉ');?></strong></div>
            <div class="item-content"><i class="fas fa-map-marker-alt"></i> <?= Html::encode($model->getFullAddress());?></div>
        </div>
        <div class="item-detail">
            <div class="item-label"><strong><?= Yii::t('checkin', 'Ngày tạo');?></strong></div>
            <div class="item-content"><?= Yii::$app->formatter->asDate($model->created_at, 'long');?></div>
        </div>
    </div>
</div>

backend/views/patient/detail/_prescription.php
<?php
use yii\grid\GridView;
use common\components\utils\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use common\grid\EnumColumn;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use common\components\utils\PermissionConstant;
use common\models\Prescription;
use kartik\widgets\Select2;

$diagnose = ['' => Yii::t('backend', 'Tất cả')] + ArrayHelper::map(\common\models\DiseaseGroup::find()->all(), 'id', 'name');

echo GridView::widget([
    'layout' => "{items}\n{pager}",
    'options' => [
        'class' => 'table-responsive'
    ],
    'tableOptions' => [
        'class' => [
            'table align-items-center table-striped table-flush',
        ]
    ],
    'headerRowOptions' => [
        'class' => [
            'thead-light'
        ]
    ],
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        [
            'attribute' => 'id',
            'contentOptions' => [
                'style' => 'width: 40px'
            ],
        ],
        [
            'attribute' => 'doctor_name',
            'contentOptions' => [
                'style' => 'word-break: break-word; white-space: normal;',
            ],
            'label' => Yii::t('backend', 'Bác sĩ'),
        ],
        [
            'attribute' => 'doctor_phone',
            'label' => 'SĐT Bác',
            'contentOptions' => [
                'style' => 'width: 100px'
            ],
        ],
        [
            'attribute' => 'is_use_insurance',
            'class' => \common\grid\EnumColumn::class,
            'enum' => Prescription::yesno(),
            'filter' => Select2::widget([
                'model' => $searchModel,
                'attribute' => 'is_use_insurance',
                'data' => ['' => Yii::t('backend', 'Tất cả')] + Prescription::yesno(),
            ]),
            'contentOptions' => [
                'width' => '10%',
                'style' => 'word-break: break-word; white-space: normal;',
            ],
        ],
        [
            'attribute' => 'arr_diagnoses',
            'contentOptions' => [
                'width' => '10%',
                'style' => 'word-break: break-word; white-space: normal;',
            ],
            'value' => function($model) {
                return implode(' / ', ArrayHelper::getColumn($model->diagnoses, 'name'));
            },
            'filter' => Select2::widget([
                'model' => $searchModel,
                'attribute' => 'arr_diagnoses',
                'data' => $diagnose,
                'options' => [
                    'id' => 'sel-diagnose'
                ],
            ]),
        ],
        [
            'class' => \common\grid\EnumColumn::class,
            'attribute' => 'status',
            'enum' => Prescription::statuses(),
            'filter' => Select2::widget([
                'model' => $searchModel,
                'attribute' => 'status',
                'data' => ['' => Yii::t('backend', 'Tất cả')] + Prescription::statuses(),
            ]),
            'contentOptions' => [
                'width' => '10%',
                'style' => 'word-break: break-word; white-space: normal;',
            ],
        ],
        [
            'class' => \common\widgets\ActionColumn::class,
            'contentOptions' => [
                'class' => 'table-actions',
                'style' => 'width: 32px'
            ],
            'template' => '<div class="dropdown">
                    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                      {view}{update}{delete}
                    </div>
                  </div>',
            'urlCreator' => function( $action, $model, $key, $index ){
                if ($action == "view") {
                    return Url::to(['/prescription/view', 'id' => $key]);
                } else if ($action == "update") {
                    return Url::to(['/prescription/update', 'id' => $key]);
                } else if ($action == "delete") {
                    return Url::to(['/prescription/delete', 'id' => $key]);
                }
            },
            'buttons' => [
                'view' => function ($url, $model) {
                    $attributes = [
                        'class' => 'dropdown-item',
                        'data-toggle' => 'tooltip',
                        'title' => Yii::t('checkin', 'Xem')
                    ];
                    return Html::a(Yii::t('checkin', 'Xem'), $url, $attributes, [PermissionConstant::VIEW_PRESCRIPTION]);
                },
                'update' => function ($url, $model) {
                    $attributes = [
                        'class' => 'dropdown-item',
                        'data-toggle' => 'tooltip',
                        'title' => Yii::t('checkin', 'Cập nhật')
                    ];
                    return Html::a(Yii::t('checkin', 'Cập nhật'), $url, $attributes, [PermissionConstant::UPDATE_PRESCRIPTION]);
                },
                'delete' => function ($url, $model) {
                    $attributes = [
                        'class' => 'dropdown-item',
                        'data-toggle' => 'tooltip',
                        'title' => Yii::t('checkin', 'Xóa'),
                        'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                        'data-method' => 'post',
                    ];
                    return Html::a(Yii::t('checkin', 'Xóa'), $url, $attributes, [PermissionConstant::DELETE_PRESCRIPTION]);
                }
            ]
        ],
    ],
]);
?>