common/models/Prescription.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "prescription".
 *
 * @property int $id
 * @property int $doctor_id
 * @property int $patient_id
 * @property string $insurance_number
 * @property int $is_use_insurance 0: Khong, 1: Co
 * @property float $insurance_rate
 * @property int|null $total_amount
 * @property string $note
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property int|null $re_examination
 * @property string|null $re_examination_date
 * @property int $store_id
 *
 * @property Doctor $doctor
 * @property Store $store
 * @property Patient $patient
 * @property PrescriptionDetail[] $prescriptionDetails
 * @property PrescriptionDiagnose[] $prescriptionDiagnoses
 */
class Prescription extends GeneralModel
{
    const STATUS_DRAFT = 0; // đang tạo
    const STATUS_DELIVERY_TO_STORE = 1; // đã chuyển cho nhà thuốc
    const STATUS_DONE = 2; // hoàn thành||đã giao

    public $arr_diagnoses;

    //for search
    public $doctor_name;
    public $doctor_phone;
    public $patient_name;
    public $patient_province;
    public $patient_district;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'prescription';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['doctor_id', 'patient_id', 'is_use_insurance'], 'required'],
            [['doctor_id', 'patient_id', 'is_use_insurance', 'total_amount', 'status', 'created_at', 'updated_at', 're_examination'], 'integer'],
            [['insurance_rate'], 'number'],
            [['re_examination_date'], 'safe'],
            [['insurance_number'], 'string', 'max' => 50],
            [['note'], 'string', 'max' => 1024],
            [['doctor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Doctor::className(), 'targetAttribute' => ['doctor_id' => 'id']],
            [['patient_id'], 'exist', 'skipOnError' => true, 'targetClass' => Patient::className(), 'targetAttribute' => ['patient_id' => 'id']],
            [['arr_diagnoses'], 'safe'],
            ['insurance_number', 'required', 'when' => function ($model) {
                return $model->is_use_insurance == 1;
            }, 'whenClient' => "function (attribute, value) {
                return $('#sel-insurance').val() == 1;
            }"],
            ['insurance_rate', 'required', 'when' => function ($model) {
                            return $model->is_use_insurance == 1;
                        }, 'whenClient' => "function (attribute, value) {
                return $('#sel-insurance').val() == 1;
            }"],
            ['re_examination_date', 'required', 'when' => function ($model) {
                return $model->re_examination == 1;
            },
             'whenClient' => "function (attribute, value) {
                return $('input[name=\"Prescription[re_examination]\"]:checked').val() == 1;
            }"
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('common', 'ID'),
            'doctor_id' => Yii::t('common', 'Bác sĩ'),
            'patient_id' => Yii::t('common', 'Khách hàng'),
            'insurance_number' => Yii::t('common', 'Số BHYT'),
            'is_use_insurance' => Yii::t('common', 'BHYT'),
            'insurance_rate' => Yii::t('common', '% BHYT'),
            'total_amount' => Yii::t('common', 'Tổng tiền'),
            'note' => Yii::t('common', 'Lời dặn của bác sĩ'),
            'status' => Yii::t('common', 'Trạng thái'),
            'created_at' => Yii::t('common', 'Tạo lúc'),
            'updated_at' => Yii::t('common', 'Cập nhật lúc'),
            'arr_diagnoses' => Yii::t('common', 'Chẩn đoán'),
            're_examination' => Yii::t('app', 'Hẹn tái khám'),
            're_examination_date' => Yii::t('app', 'Ngày tái khám'),
            'store_id' => Yii::t('app', 'Nhà thuốc'),
        ];
    }

    public static function statuses()
    {
        return [
            self::STATUS_DRAFT => Yii::t('common', 'Đang tạo'),
            self::STATUS_DELIVERY_TO_STORE => Yii::t('common', 'Đã chuyển nhà thuốc'),
            self::STATUS_DONE => Yii::t('common', 'Hoàn thành'),
            self::STATUS_DELETED => Yii::t('common', 'Đã huỷ'),
        ];
    }

    public static function statusNotes()
    {
        return [
            self::STATUS_DRAFT => Yii::t('common', 'Bạn chưa điền đầy đủ thông tin của toa thuốc, hãy “Sửa” để cập nhật hoàn chỉnh và in toa hoặc “Xóa”'),
            self::STATUS_DELIVERY_TO_STORE => Yii::t('common', 'Đã chuyển nhà thuốc'),
            self::STATUS_DONE => Yii::t('common', 'Đơn thuốc đã in, đang chờ lấy thuốc trực tiếp hoặc thông qua Nhà thuốc'),
            self::STATUS_DELETED => Yii::t('common', 'Đơn thuốc đã bị hủy'),
        ];
    }

    public static function insuranceRates()
    {
        return [10 => '10%', 20 => '20%', 30 => '30%', 40 => '40%', 50 => '50%', 60 => '60%', 70 => '70%', 80 => '80%', 90 => '90%', 100 => '100%'];
    }
    /**
     * Gets query for [[Doctor]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDoctor()
    {
        return $this->hasOne(Doctor::className(), ['id' => 'doctor_id']);
    }

    /**
     * Gets query for [[Patient]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPatient()
    {
        return $this->hasOne(Patient::className(), ['id' => 'patient_id']);
    }

    public function getStore()
    {
        return $this->hasOne(Store::className(), ['id' => 'store_id']);
    }

    /**
     * Gets query for [[PrescriptionDetails]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPrescriptionDetails()
    {
        return $this->hasMany(PrescriptionDetail::className(), ['prescription_id' => 'id']);
    }

    /**
     * Gets query for [[PrescriptionDiagnoses]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPrescriptionDiagnoses()
    {
        return $this->hasMany(PrescriptionDiagnose::className(), ['prescription_id' => 'id']);
    }

    public function getDiagnoses() {
        return $this->hasMany(DiseaseGroup::className(), ['id' => 'diagnose_id'])
                    ->via('prescriptionDiagnoses');
    }

    /**
     * @inheritdoc
     */
    public function afterFind()
    {
        parent::afterFind();
        $this->arr_diagnoses = ArrayHelper::getColumn($this->prescriptionDiagnoses, 'diagnose_id');
        $this->re_examination_date = $this->re_examination_date ? date("d/m/Y H:i", strtotime($this->re_examination_date)) : null;
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        $re_examination_date = \DateTime::createFromFormat('d/m/Y H:i', $this->re_examination_date);
        if ($re_examination_date) {
            $this->re_examination_date = $re_examination_date->format('Y-m-d H:i:s');
        }
        $action = Yii::$app->request->post('btn-submit', 'save');
        if ($action == 'done') {
            $this->status = self::STATUS_DONE;
        }
        return true;
    }

    public function afterSave ( $insert, $changedAttributes )
    {
        parent::afterSave($insert, $changedAttributes);
        $this->saveSchedule();
        $this->saveDiagnoses();
    }

    public function saveSchedule()
    {
        $model = ExaminationSchedule::findOne(['prescription_id' => $this->id]);
        if ($this->re_examination) {
            if (!$model) {
                $model = new ExaminationSchedule();
                $model->prescription_id = $this->id;
                $model->doctor_id = $this->doctor_id;
                $model->patient_id = $this->patient_id;
            }
            $model->date = $this->re_examination_date;
            $model->note = $this->note;
            $model->save();
        } else { //delete schedule
            if ($model && $model->delete());
        }
    }

    public function saveDiagnoses()
    {
        $this->arr_diagnoses = is_array($this->arr_diagnoses) ? $this->arr_diagnoses : [];
        if ((isset($this->relatedRecords['prescriptionDiagnoses']) && diff_2array(ArrayHelper::getColumn($this->relatedRecords['prescriptionDiagnoses'], 'diagnose_id'), $this->arr_diagnoses)) || empty($this->relatedRecords['prescriptionDiagnoses'])) {
            if (!$this->isNewRecord) {
                // update // delete all
                PrescriptionDiagnose::deleteAll('prescription_id = :id', array('id' => $this->id));
            }
            // insert it.
            foreach ($this->arr_diagnoses as $id) {
                $model = new PrescriptionDiagnose();
                $model->prescription_id = $this->id;
                $model->diagnose_id = $id;
                $model->save();
            }
        }
    }

    public function getCode()
    {
        return "DT{$this->id}-" . date('dmY', $this->created_at);
    }
}

backend/views/prescription/view/_view.php
<?php
use yii\helpers\ArrayHelper;
use \yii\helpers\Html;
$prescriptionDetails = ArrayHelper::index($model->prescriptionDetails, null, 'type');
$drugged_time = ArrayHelper::map(\common\models\DruggedTime::find()->all(), 'id', 'name');
$dosage_form = ArrayHelper::map(\common\models\DosageForm::find()->all(), 'id', 'name');
$rate = @\common\models\Prescription::insuranceRates()[$model->insurance_rate];
$doctorSettings = ArrayHelper::map(\common\models\DoctorSetting::find()->where(['doctor_id' => $model->doctor->id])->asArray()->all(), 'key', 'value');
$showHeader = !empty($doctorSettings['logo']) + !empty($doctorSettings['medical_name']) + !empty($doctorSettings['clinic_name']) +
    !empty($doctorSettings['clinic_phone']) + !empty($doctorSettings['barcode']) + !empty($doctorSettings['medical_code']) + !empty($doctorSettings['no_of_record']);
?>
<div class="prescription-view">
  <?php if($showHeader): ?>
    <div class="form-header">
      <div class="row">
        <div class="col-7 col-sm-6 view-left-header">
          <div class="row align-items-center">
              <?php if(!empty($doctorSettings['logo'])): ?>
                <div class="col col-logo"><?= Html::img(\Yii::$app->params['baseUrl'] .'/'. $doctorSettings['logo'])?></div>
              <?php endif;?>
            <div class="col">
                <?php if(!empty($doctorSettings['medical_name'])): ?>
                  <div><label class="label-text"><?= Html::encode($doctorSettings['medical_name']);?></label></div>
                <?php endif;?>

                <?php if(!empty($doctorSettings['clinic_name'])): ?>
                  <div><label class="label-text"><?= Html::encode(@$doctorSettings['clinic_name']);?></label></div>
                <?php endif;?>

                <?php if(!empty($doctorSettings['clinic_phone'])): ?>
                  <div><label class="label-text">Liên hệ:</label><?= Html::encode(@$doctorSettings['clinic_phone']);?></div>
                <?php endif;?>
            </div>
          </div>
        </div>
        <div class="col-5 col-sm-6 text-center view-right-header">
          <div class="col-barcode">
              <?php if(!empty($doctorSettings['barcode'])): ?>
                  <?= Html::img(\Yii::$app->params['baseUrl'] .'/'. $doctorSettings['barcode'], ['class' => 'img-barcode'])?>
              <?php endif;?>

              <?php if(!empty($doctorSettings['medical_code'])): ?>
                <div><label class="label-text">Mã Y Tế</label><?= Html::encode(@$doctorSettings['medical_code']);?></div>
              <?php endif;?>

              <?php if(!empty($doctorSettings['no_of_record'])): ?>
                <div><label class="label-text">Số hồ sơ</label><?= Html::encode(@$doctorSettings['no_of_record']);?></div>
              <?php endif;?>
          </div>
        </div>
      </div>
    </div>
  <?php endif;?>
  <div class="row block-info">
    <div class="col-6 mb-10 text-left">
      <span class="label-text">Mã đơn thuốc</span>DT<?=$model->id?>-<?=date('dmY', $model->created_at);?>
    </div>
    <div class="col-6 mb-10 text-right">
      <span class="label-text">Ngày tạo</span><?=date('d/m/Y', $model->created_at);?><span class="ml-3"><?= str_replace('{%1}', 'h', date('H{%1}i', $model->created_at));?></span>
    </div>
    <div class="col-12">
      <h1 class="text-center font-weight-bold text-uppercase">Toa thuốc</h1>
    </div>
    <div class="<?= isset($print) ? 'col-6' : 'col-sm-6';?> mb-10"><label class="min-width label-text">Họ và tên</label><?=Html::encode($model->patient->fullname)?></div>
    <div class="<?= isset($print) ? 'col-3' : 'col-sm-3 col-6';?> mb-10"><label class="label-text">Độ tuổi</label><?=Html::encode($model->patient->getYearOld())?></div>
    <div class="<?= isset($print) ? 'col-3' : 'col-sm-3 col-6';?> mb-10"><label class="label-text">Giới tính</label><?=@\common\models\Patient::genders()[$model->patient->gender]?></div>

    <div class="<?= isset($print) ? 'col-6' : 'col-sm-6 col-12';?> mb-10"><label class="min-width label-text">Số điện thoại</label><?=Html::encode($model->patient->phone)?></div>
    <div class="<?= isset($print) ? 'col-6' : 'col-sm-6 col-12';?> mb-10"><label class="label-text">Email</label><?=Html::encode($model->patient->email)?></div>

    <div class="col-12 mb-10"><label class="min-width label-text">Địa chỉ</label><?=Html::encode($model->patient->getFullAddress())?></div>

    <div class="col-sm-4 col-6 mb-10"><label class="min-width label-text">Số BHYT</label><?=Html::encode($model->insurance_number)?></div>
    <div class="col-sm-4 col-6 mb-10"><label class="label-text"><?=$model->is_use_insurance ? "Có BHYT ({$rate})" : 'Không BHYT';?></label></div>
    <div class="col-12 mb-10"><label class="label-text">Chẩn đoán</label><?= implode(' / ', \yii\helpers\ArrayHelper::getColumn($model->diagnoses, 'name'));?></div>
  </div>
  <div class="block-medicine">
      <?php foreach ($prescriptionDetails as $type => $prescription): ?>
        <h4 class="heading-prescription"><?= \common\models\PrescriptionDetail::types()[$type]?></h4>
        <table class="table table-borderless">
            <?php foreach ($prescription as $index => $medicine): ?>
              <tr>
                <td class="column-index text-center"><strong><?=($index+1);?></strong></td>
                <td>
                  <div class=""><strong><?=$medicine->medicine->name?></strong></div>
                </td>
                <td class="column-amount text-center"><strong><?=$medicine->amount?></strong></td>
                <td class="column-dosage-form text-center"><strong><?=@$dosage_form[$medicine->dosage_form_id]?></strong></td>
              </tr>
              <tr>
                <td class="column-index text-center"></td>
                <td colspan="3">
                  <div class="mb-2"><span class="text-sub">Liều dùng</span> <span class="text-mute text-small">(<?= Html::encode(@$dosage_form[$medicine->dosage_form_id]);?>)</span></div>
                  <div>
                    <span class="mr-4"><label class="label-text">Sáng</label><?=(int)$medicine->amount_morning?> <?=Html::encode(@$dosage_form[$medicine->dosage_form_id])?></span>
                    <span class="mr-4"><label class="label-text">Trưa</label><?=(int)$medicine->amount_noon?> <?=Html::encode(@$dosage_form[$medicine->dosage_form_id])?></span>
                    <span class="mr-4"><label class="label-text">Chiều</label><?=(int)$medicine->amount_afternoon?> <?=Html::encode(@$dosage_form[$medicine->dosage_form_id])?></span>
                    <span class="<?= isset($print) ? '' : 'view-time-drug';?>"><label class="label-text"><?=Html::encode(@\common\models\PrescriptionDetail::timeUses()[$medicine->time_of_use])?></label><?= Html::encode(@$drugged_time[$medicine->drugged_time])?></span>
                  </div>
                </td>
              </tr>
            <?php endforeach;?>
        </table>
        <h6 class="total-line">Cộng khoản: <span class="total-line"><?= count($prescription);?></span></h6>
      <?php endforeach;?>
  </div>
  <div class="block-note">
    <h4 class="heading-prescription">Lời dặn của bác sĩ</h4>
    <div>
      <i class="text-sub"><?=\yii\helpers\Html::encode($model->note);?></i>
    </div>
      <?php
      if ($model->re_examination) {
          echo "<p class='mt-2'><i class=\"text-sub\">hẹn tái khám vào ngày &nbsp;{$model->re_examination_date}</i></p>";
      }
      ?>

  </div>
  <div class="row align-items-end block-bottom">
    <div class="col-sm-6 col-5">
      <div><strong>Người nhận thuốc</strong> <span class="text-mute text-small">(Ký tên)</span></div>
    </div>
    <div class="col-sm-6 col-7 text-center">
      <div class="float-right">
        <div class="font-italic"><?= sprintf("Ngày &nbsp; %s &nbsp; tháng  &nbsp; %s &nbsp; năm &nbsp; %s", date('d', $model->created_at), date('m', $model->created_at), date('Y', $model->created_at));?></div>
        <div class="font-weight-bold text-uppercase mt-4">Bác sĩ khám bệnh</div>
        <div class="sign-space"></div>
        <div class="mb-4"><strong>Bác sĩ <span class="text-uppercase"><?= Html::encode($model->doctor->fullname);?></span></strong></div>
        <div><strong>Tổng tiền thuốc </strong><span id="total-amount"><?= Yii::$app->formatter->asInteger($model->total_amount);?></span> VNĐ</div>
      </div>
    </div>
  </div>
</div>